[package]
name = "qopt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Search strategies, cost models, and resynthesis orchestration for GUOQ."

[dependencies]
qcircuit.workspace = true
qsemantics.workspace = true
qrules.workspace = true
qresynth.workspace = true
rand.workspace = true
rayon.workspace = true
rand_chacha.workspace = true
rustc-hash.workspace = true
serde = { workspace = true }
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
anyhow.workspace = true
tempfile.workspace = true

[lints]
workspace = true
