# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
 
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Open wisq PR with new JAR 

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package -DskipTests
    - name: Send pull-request to wisq repo
      run: |
        LATEST_TAG=$(git describe --tags --always --abbrev=0)
        REPOSITORY="qqq-wisc/wisq"
        FOLDER="bin/$REPOSITORY"
        BRANCH_NAME="upgate-guoq-jar-$LATEST_TAG"

        # Clone the remote repository and change working directory to the
        # folder it was cloned to.
        git clone \
          --depth=1 \
          --branch=main \
          https://qqq-wisc:${{ secrets.ACCESS_TOKEN }}@github.com/$REPOSITORY \
          $FOLDER

        cd $FOLDER

        # Setup the committers identity.
        git config user.email "github-actions@wisc.edu"
        git config user.name "GitHub Actions"

        # Create a new feature branch for the changes.
        git checkout -b $BRANCH_NAME

        # Update GUOQ JAR and resynth.py to the latest version.
        cp -R ../../../target/GUOQ-1.0-jar-with-dependencies.jar src/wisq/lib
        cp -R ../../../resynth.py src/wisq

        # Commit the changes and push the feature branch to origin
        git add .
        git commit -m "Update GUOQ JAR to $LATEST_TAG"
        git push origin $BRANCH_NAME

        # Store the PAT in a file that can be accessed by the
        # GitHub CLI.
        echo "${{ secrets.ACCESS_TOKEN }}" > token.txt

        # Authorize GitHub CLI for the current repository and
        # create a pull-requests containing the updates.
        gh auth login --with-token < token.txt
        gh pr create \
          --body "" \
          --title "Update GUOQ JAR to $LATEST_TAG" \
          --head "$BRANCH_NAME" \
          --base "main"
      
    # # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
